#  “Вычисления с помощью Numpy”

Задание 1

In [31]:
import numpy as np

# Создаем массив a размером 5x2
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

# Находим среднее значение по каждому столбцу
mean_a = a.mean(axis=0)

print("Массив a:")
print(a)

print()
print("Среднее значение по каждому признаку:")
print(mean_a)

Массив a:
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]

Среднее значение по каждому признаку:
[2.  8.4]


Задание 2

In [32]:
import numpy as np

# Создаем массив a размером 5x2
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

# Находим среднее значение по каждому столбцу
mean_a = a.mean(axis=0)

# Вычисляем массив a_centered
a_centered = a - mean_a

print("Массив a:")
print(a)

print()
print("Среднее значение по каждому признаку:")
print(mean_a)

print()
print("Центрированный массив a_centered:")
print(a_centered)

Массив a:
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]

Среднее значение по каждому признаку:
[2.  8.4]

Центрированный массив a_centered:
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3

In [33]:
import numpy as np

# Создаем массив a размером 5x2
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

# Находим среднее значение по каждому столбцу
mean_a = a.mean(axis=0)

# Вычисляем массив a_centered
a_centered = a - mean_a

# Находим скалярное произведение столбцов массива a_centered
centered_spa = np.dot(a_centered.T[0], a_centered.T[1])

print("Массив a:")
print(a)

print()
print("Среднее значение по каждому признаку:")
print(mean_a)

print()
print("Центрированный массив a_centered:")
print(a_centered)

print()
print("Скалярное произведение столбцов a_centered:", centered_spa)

N = len(a_centered)  # число наблюдений
centered_sp = centered_spa / (N - 1)
print("centered_sp:", centered_sp)

Массив a:
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]

Среднее значение по каждому признаку:
[2.  8.4]

Центрированный массив a_centered:
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]

Скалярное произведение столбцов a_centered: 8.0
centered_sp: 2.0


In [35]:
import numpy as np

# Создаем массив a размером 5x2
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

# Находим среднее значение по каждому столбцу
mean_a = a.mean(axis=0)

# Вычисляем массив a_centered
a_centered = a - mean_a

# Находим скалярное произведение столбцов массива a_centered
centered_spa = np.dot(a_centered.T[0], a_centered.T[1])

N = len(a_centered)  # число наблюдений
centered_sp = centered_spa / (N - 1)
print("centered_sp:", centered_sp)

# Вычислим ковариацию с помощью функции np.cov
m = a_centered.transpose()
covar_matrix = np.cov(m)

print("Ковариационная матрица:")
print(covar_matrix)

covariance = covar_matrix[0, 1]
print("Значение ковариации:", covariance)

centered_sp: 2.0
Ковариационная матрица:
[[1.  2. ]
 [2.  4.3]]
Значение ковариации: 2.0


# 'работа в Pandas'

задание 1

In [36]:
import pandas as pd

# Создаем датафрейм authors со столбцами author_id и author_name
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})

# Выводим датафрейм на экран
print(authors)

# Создаём датафрейм book со столбцами author_id, book_title и price
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [500, 400, 300, 350, 450, 600, 200]
})

# Выводим датафрейм на экран
print(book)


   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
   author_id            book_title  price
0          1           Отцы и дети    500
1          1                 Рудин    400
2          1     Дворянское гнездо    300
3          2      Толстый и тонкий    350
4          2       Дама с собачкой    450
5          3                 Гроза    600
6          3  Таланты и поклонники    200


задание 2

In [38]:
import pandas as pd

# Создаем датафрейм authors со столбцами author_id и author_name
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})

# Выводим датафрейм на экран
print(authors)

# Создаём датафрейм book со столбцами author_id, book_title и price
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [500, 400, 300, 350, 450, 600, 200]
})

# Соединяем датафреймы authors и book по полю author_id
authors_price = pd.merge(authors, book, on='author_id')

# Выводим полученный датафрейм на экран
print(authors_price)


   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    500
1          1    Тургенев                 Рудин    400
2          1    Тургенев     Дворянское гнездо    300
3          2       Чехов      Толстый и тонкий    350
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    600
6          3  Островский  Таланты и поклонники    200


задание 3

In [39]:
import pandas as pd

# Создаем датафрейм authors со столбцами author_id и author_name
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})

# Выводим датафрейм на экран
print(authors)

# Создаём датафрейм book со столбцами author_id, book_title и price
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [500, 400, 300, 350, 450, 600, 200]
})

# Соединяем датафреймы authors и book по полю author_id
authors_price = pd.merge(authors, book, on='author_id')

# Сортируем датафрейм по цене в порядке убывания
authors_price.sort_values(by=['price'], ascending=False, inplace=True)

# Получаем первые пять строк
top5 = authors_price.head(5)

# Выводим полученный датафрейм на экран
print(top5)


   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
   author_id author_name        book_title  price
5          3  Островский             Гроза    600
0          1    Тургенев       Отцы и дети    500
4          2       Чехов   Дама с собачкой    450
1          1    Тургенев             Рудин    400
3          2       Чехов  Толстый и тонкий    350


задание 4

In [40]:
import pandas as pd

# Создаем датафрейм authors со столбцами author_id и author_name
authors = pd.DataFrame({
    'author_id': [1, 2, 3],
    'author_name': ['Тургенев', 'Чехов', 'Островский']
})

# Выводим датафрейм на экран
print(authors)

# Создаём датафрейм book со столбцами author_id, book_title и price
book = pd.DataFrame({
    'author_id': [1, 1, 1, 2, 2, 3, 3],
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
    'price': [500, 400, 300, 350, 450, 600, 200]
})

# Соединяем датафреймы authors и book по полю author_id
authors_price = pd.merge(authors, book, on='author_id')

# Группируем данные по авторам
grouped = authors_price.groupby('author_name')

# Получаем минимальную, максимальную и среднюю цену для каждого автора
min_price = grouped['price'].min()
max_price = grouped['price'].max()
mean_price = grouped['price'].mean()

# Добавляем полученные значения в новый датафрейм
authors_stat = pd.DataFrame({'author_name': grouped.groups.values,
                            'min_price': min_price,
                            'max_price': max_price,
                            'mean_price': mean_price})

# Выводим полученный датафрейм на экран
print(authors_stat)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский
                                                   author_name  min_price  \
author_name                                                                 
Островский   <built-in method values of PrettyDict object a...        200   
Тургенев     <built-in method values of PrettyDict object a...        300   
Чехов        <built-in method values of PrettyDict object a...        350   

             max_price  mean_price  
author_name                         
Островский         600         400  
Тургенев           500         400  
Чехов              450         400  


задание 5

In [44]:
import pandas as pd
import numpy as np

# Создание исходного датафрейма authors_price
authors_price = pd.DataFrame({
    'author_id': [1, 2, 3, 4, 5],
    'author_name': ['Тургенев', 'Чехов', 'Островский', 'Гоголь', 'Достоевский'],
    'book_title': ['Отцы и дети', 'Толстый и тонкий', 'Гроза', 'Толстый и тонкий', 'Идиот'],
    'price': [450, 300, 350, 500, 450]
})

# Добавление столбца 'cover'
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая']

# Создание сводной таблицы с суммарной стоимостью книг в твердой и мягкой обложке по авторам
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover', aggfunc=np.sum, fill_value=0)

# Сохранение датасета в файл формата pickle
book_info.to_pickle("book_info.pkl")

# Загрузка сохраненного датасета
book_info2 = pd.read_pickle("book_info.pkl")

# Проверка идентичности датафреймов book_info и book_info2
if book_info.equals(book_info2):
    print("Датасеты book_info и book_info2 идентичны.")
else:
    print("Датасеты book_info и book_info2 не идентичны.")

Датасеты book_info и book_info2 идентичны.
